export const statusLabels: Record<string, string> = {
  pendiente: 'Pendiente',
  revisada: 'Revisada',
  en_ruta: 'En ruta',
  entregada: 'Entregada',
  activa: 'Activa',
  cerrada: 'Cerrada',
  completada: 'Completada',
  incidencia: 'Incidencia',
  pago_pendiente: 'Pago pendiente',
  por_verificar: 'Por verificar',
  confirmada: 'Confirmada',
  rechazada: 'Rechazada',
  cancelada: 'Cancelada',
}
