import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import type { Letter } from '../lib/types'

export function LetterEditorDialog({ onClose, onSave }: { onClose: () => void; onSave: (letter: Letter) => Promise<void> }) {
  const [form, setForm] = useState({ sender: '', senderPhone: '', recipient: '', recipientPhone: '', origin: '', destination: '', serviceDate: new Date().toISOString().slice(0, 10), species: 'Perro', breed: '', size: 'mediano' as const })
  const [saving, setSaving] = useState(false)
  const update = (field: keyof typeof form, value: string) => setForm((current) => ({ ...current, [field]: value }))
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); try { await onSave({ id: `CARTA DE PORTE Nº ${new Date().getFullYear()}-${Date.now().toString().slice(-6)}`, sender: form.sender, senderPhone: form.senderPhone, recipient: form.recipient, recipientPhone: form.recipientPhone, origin: form.origin, destination: form.destination, route: 'Sin asignar', serviceDate: form.serviceDate, status: 'revisada', importedAt: new Date().toLocaleString('es-ES'), animals: [{ id: crypto.randomUUID(), species: form.species, breed: form.breed, size: form.size }] }); onClose() } finally { setSaving(false) } }
  return <Dialog open onOpenChange={(open) => { if (!open) onClose() }}><DialogContent className="dialog-card !w-[calc(100%-2.5rem)] !max-w-[650px] !p-[26px]"><DialogHeader><DialogTitle>Nueva carta de porte</DialogTitle><DialogDescription>Crea una carta desde la oficina. Los datos quedarán disponibles para rutas, furgón y facturación.</DialogDescription></DialogHeader><form className="client-form" onSubmit={submit}><Label>Remitente<Input required value={form.sender} onChange={(event) => update('sender', event.target.value)} /></Label><Label>Teléfono remitente<Input required value={form.senderPhone} onChange={(event) => update('senderPhone', event.target.value)} /></Label><Label>Destinatario<Input required value={form.recipient} onChange={(event) => update('recipient', event.target.value)} /></Label><Label>Teléfono destinatario<Input required value={form.recipientPhone} onChange={(event) => update('recipientPhone', event.target.value)} /></Label><Label>Origen<Input required value={form.origin} onChange={(event) => update('origin', event.target.value)} /></Label><Label>Destino<Input required value={form.destination} onChange={(event) => update('destination', event.target.value)} /></Label><Label>Fecha de servicio<Input required type="date" value={form.serviceDate} onChange={(event) => update('serviceDate', event.target.value)} /></Label><Label>Raza<Input required value={form.breed} onChange={(event) => update('breed', event.target.value)} /></Label><Label>Especie<Input required value={form.species} onChange={(event) => update('species', event.target.value)} /></Label><Label>Tamaño<select value={form.size} onChange={(event) => update('size', event.target.value)}><option value="pequeno">Pequeño</option><option value="mediano">Mediano</option><option value="grande">Grande</option></select></Label><Button type="submit" className="dialog-submit" disabled={saving}>{saving ? 'Guardando…' : 'Crear carta'}</Button></form></DialogContent></Dialog>
}
